[package]
name = "leesp"
version = "0.1.2"
authors = ["phreppo <parolini.francesco.1@gmail.com>"]

# lalrop deps
[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
lalrpop-util = "0.16.3"
regex = "0.2.1"


